# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Store.create(name: "superstore")
Store.create(name: "calary co-op")
Brand.create(name: "unbranded")
Brand.create(name: "president's choice")
Unit.create(name: "pound")
Unit.create(name: "number")
Unit.create(name: "dozen")
Unit.create(name: "gram")
Unit.create(name: "liter")
Unit.create(name: "kilogram")
Unit.create(name: "meter")
Unit.create(name: "yard")
Unit.create(name: "set")
ListType.create(name: "private", description: "for your eyes only")
ListType.create(name: "shared", description: "shared with other people")
ListType.create(name: "public", description: "shared with the whole world")
ItemCategory.create(name: "Baby stuff", description: "items required specifically by babies")
ItemCategory.create(name: "Baked goods", description: "items bakery section")
ItemCategory.create(name: "Baking", description: "items required baking purposes")
ItemCategory.create(name: "Beans", description: "self explanatory")
ItemCategory.create(name: "Beverages", description: "soft and hard drinks")
ItemCategory.create(name: "Canned foods", description: "items canned generally with preservatives")
ItemCategory.create(name: "Cleaning products", description: "items required for cleaning")
ItemCategory.create(name: "Condiments / Sauces", description: "self explanatory")
ItemCategory.create(name: "Dairy and Cheese", description: "items of milk and by-products")
ItemCategory.create(name: "Fresh fruits", description: "self explanatory")
ItemCategory.create(name: "Fresh vegetables", description: "self explanatory")
ItemCategory.create(name: "Frozen foods", description: "items required to be frozed below 0 degree C")
ItemCategory.create(name: "Grains", description: "full grains")
ItemCategory.create(name: "Kitchen", description: "kitchen consumable items")
ItemCategory.create(name: "Meat", description: "self explanatory")
ItemCategory.create(name: "Medicine", description: "self explanatory, both off the shelf and prescription")
ItemCategory.create(name: "Nuts", description: "self explanatory")
ItemCategory.create(name: "Office supplies", description: "paper, cd-rom, writing material, markers etc")
ItemCategory.create(name: "Other stuff", description: "not categorized anywhere")
ItemCategory.create(name: "Personal care", description: "hygene and personal care items")
ItemCategory.create(name: "Pets", description: "items required specifically by pets")
ItemCategory.create(name: "Refrigerated items", description: "items required to be kepts cooler than room temperatures")
ItemCategory.create(name: "Seafood", description: "self explanatory")
ItemCategory.create(name: "Seeds", description: "self explanatory")
ItemCategory.create(name: "Snacks", description: "self explanatory")
ItemCategory.create(name: "Spices & herbs", description: "self explanatory")
Item.create(name: "Air freshener")
Item.create(name: "Aluminum foil")
Item.create(name: "Antacid")
Item.create(name: "Antibiotic")
Item.create(name: "Antidiarrheal")
Item.create(name: "Antiperspirant / Deodorant")
Item.create(name: "Apples")
Item.create(name: "Applesauce")
Item.create(name: "Asparagus")
Item.create(name: "Aspirin")
Item.create(name: "Automotive")
Item.create(name: "Avocados")
Item.create(name: "Baby food")
Item.create(name: "Baby wash")
Item.create(name: "Bacon / Sausage")
Item.create(name: "Bagels / Croissants")
Item.create(name: "Bagels")
Item.create(name: "Baked beans")
Item.create(name: "Baking powder / Soda")
Item.create(name: "Bananas")
Item.create(name: "Band-aids / Medical")
Item.create(name: "Basil")
Item.create(name: "Bath soap / Hand soap")
Item.create(name: "Bathroom cleaner")
Item.create(name: "Batteries")
Item.create(name: "BBQ sauce")
Item.create(name: "Beef")
Item.create(name: "Beer")
Item.create(name: "Berries ")
Item.create(name: "Black pepper")
Item.create(name: "Bleach / Detergent")
Item.create(name: "Bleu cheese")
Item.create(name: "Bouillon cubes")
Item.create(name: "Bread crumbs")
Item.create(name: "Breakfasts")
Item.create(name: "Broccoli ")
Item.create(name: "Buns / Rolls")
Item.create(name: "Burritos")
Item.create(name: "Butter / Margarine")
Item.create(name: "Cake / Brownie mix")
Item.create(name: "Cake / Cookies")
Item.create(name: "Cake icing / Decorations")
Item.create(name: "Candy / Gum")
Item.create(name: "Carrots")
Item.create(name: "Cat food / Treats")
Item.create(name: "Cat litter")
Item.create(name: "Catfish")
Item.create(name: "Cauliflower")
Item.create(name: "CDRs / DVDRs")
Item.create(name: "Celery")
Item.create(name: "Cereal")
Item.create(name: "Champagne")
Item.create(name: "Charcoal / Propane")
Item.create(name: "Cheddar")
Item.create(name: "Cherries")
Item.create(name: "Chicken")
Item.create(name: "Chili")
Item.create(name: "Chip dip")
Item.create(name: "Chocolate chips / Cocoa")
Item.create(name: "Cilantro")
Item.create(name: "Cinnamon")
Item.create(name: "Club soda / Tonic")
Item.create(name: "Coffee / Filters")
Item.create(name: "Cold / Flu / Sinus")
Item.create(name: "Condoms / Other b.c.")
Item.create(name: "Cookies")
Item.create(name: "Corn")
Item.create(name: "Cosmetics")
Item.create(name: "Cottage cheese")
Item.create(name: "Cottage cheese")
Item.create(name: "Cotton swabs / Balls")
Item.create(name: "Crab")
Item.create(name: "Crackers")
Item.create(name: "Cream cheese")
Item.create(name: "Cucumbers")
Item.create(name: "Diapers")
Item.create(name: "Dish / Dishwasher soap")
Item.create(name: "Dog food / Treats")
Item.create(name: "Donuts / Pastries ")
Item.create(name: "Dried fruit")
Item.create(name: "Eggs / Fake eggs")
Item.create(name: "English muffins")
Item.create(name: "Facial cleanser")
Item.create(name: "Facial tissue")
Item.create(name: "Feminine products")
Item.create(name: "Feta")
Item.create(name: "Fish sticks")
Item.create(name: "Flea treatment")
Item.create(name: "Floss")
Item.create(name: "Flour")
Item.create(name: "Flowers / Greeting card")
Item.create(name: "Formula")
Item.create(name: "Fresh bread")
Item.create(name: "Fries / Tater tots")
Item.create(name: "Fruit juice")
Item.create(name: "Fruit")
Item.create(name: "Garbage bags")
Item.create(name: "Garlic")
Item.create(name: "Gin")
Item.create(name: "Ginger")
Item.create(name: "Glass cleaner")
Item.create(name: "Glue / Tape")
Item.create(name: "Goat cheese")
Item.create(name: "Granola bars / Mix")
Item.create(name: "Grapefruit")
Item.create(name: "Grapes")
Item.create(name: "Gravy")
Item.create(name: "Ground beef / Turkey")
Item.create(name: "Hair gel / Spray")
Item.create(name: "Half & half")
Item.create(name: "Ham / Pork")
Item.create(name: "Honey")
Item.create(name: "Hot dogs")
Item.create(name: "Hot sauce")
Item.create(name: "Hummus")
Item.create(name: "Ice cream / Sorbet")
Item.create(name: "Insect repellent")
Item.create(name: "Instant potatoes")
Item.create(name: "Jam / Jelly / Preserves")
Item.create(name: "Juice concentrate")
Item.create(name: "Juice")
Item.create(name: "Ketchup / Mustard")
Item.create(name: "Kiwis")
Item.create(name: "Lemon / Lime juice")
Item.create(name: "Lemons / Limes")
Item.create(name: "Lettuce / Greens")
Item.create(name: "Light bulbs")
Item.create(name: "Lip balm")
Item.create(name: "Lobster")
Item.create(name: "Lotion")
Item.create(name: "Lunchmeat")
Item.create(name: "Mac & cheese")
Item.create(name: "Mayonnaise")
Item.create(name: "Melon")
Item.create(name: "Milk")
Item.create(name: "Mint")
Item.create(name: "Mixers")
Item.create(name: "Moisturizing lotion")
Item.create(name: "Mop head / Vacuum bags")
Item.create(name: "Mouthwash")
Item.create(name: "Mozzarella / Provolone")
Item.create(name: "Mushrooms")
Item.create(name: "Mussels")
Item.create(name: "Napkins")
Item.create(name: "Nectarines")
Item.create(name: "Newspaper / Magazine")
Item.create(name: "Non-stick spray")
Item.create(name: "Notepad / Envelopes")
Item.create(name: "Nuts / Seeds")
Item.create(name: "Oatmeal")
Item.create(name: "Olive oil")
Item.create(name: "Olives")
Item.create(name: "Onions")
Item.create(name: "Oranges")
Item.create(name: "Oregano")
Item.create(name: "Oysters")
Item.create(name: "Pain reliever")
Item.create(name: "Pancake / Waffle mix")
Item.create(name: "Paper towels")
Item.create(name: "Paprika")
Item.create(name: "Parmesan")
Item.create(name: "Parsley")
Item.create(name: "Pasta sauce")
Item.create(name: "Pasta")
Item.create(name: "Peaches")
Item.create(name: "Peanut butter")
Item.create(name: "Pears")
Item.create(name: "Pens / Pencils")
Item.create(name: "Peppers")
Item.create(name: "Pet shampoo")
Item.create(name: "Pickles")
Item.create(name: "Pita bread")
Item.create(name: "Pizza / Pizza Rolls")
Item.create(name: "Plastic wrap")
Item.create(name: "Plums")
Item.create(name: "Popcorn")
Item.create(name: "Popsicles")
Item.create(name: "Postage stamps")
Item.create(name: "Potato / Corn chips")
Item.create(name: "Potatoes")
Item.create(name: "Prescription pick-up")
Item.create(name: "Pretzels")
Item.create(name: "Printer paper")
Item.create(name: "Provolone")
Item.create(name: "Razors / Shaving cream")
Item.create(name: "Ready-bake breads")
Item.create(name: "Red pepper")
Item.create(name: "Red wine / White wine")
Item.create(name: "Relish")
Item.create(name: "Rice")
Item.create(name: "Ricotta")
Item.create(name: "Rum")
Item.create(name: "Saké")
Item.create(name: "Salad dressing")
Item.create(name: "Salmon")
Item.create(name: "Salsa")
Item.create(name: "Salt")
Item.create(name: "Sandwich / Freezer bags")
Item.create(name: "Sandwich slices")
Item.create(name: "Shampoo / Conditioner")
Item.create(name: "Shortening")
Item.create(name: "Shrimp")
Item.create(name: "Sliced bread")
Item.create(name: "Soda pop")
Item.create(name: "Soups")
Item.create(name: "Sour cream")
Item.create(name: "Soy sauce")
Item.create(name: "Spice mix")
Item.create(name: "Spinach")
Item.create(name: "Sponges / Scrubbers")
Item.create(name: "Sports drink")
Item.create(name: "Squash")
Item.create(name: "Steak sauce")
Item.create(name: "Sugar substitute")
Item.create(name: "Sugar")
Item.create(name: "Sunblock")
Item.create(name: "Swiss")
Item.create(name: "Syrup")
Item.create(name: "Tea")
Item.create(name: "Tilapia")
Item.create(name: "Tinned meats")
Item.create(name: "Tofu")
Item.create(name: "Toilet paper")
Item.create(name: "Tomatoes")
Item.create(name: "Tomatoes")
Item.create(name: "Toothpaste")
Item.create(name: "Tortillas")
Item.create(name: "Tuna / Chicken")
Item.create(name: "Tuna")
Item.create(name: "Turkey")
Item.create(name: "TV dinners")
Item.create(name: "Vanilla extract")
Item.create(name: "Vegetable oil")
Item.create(name: "Vegetables")
Item.create(name: "Veggie burgers")
Item.create(name: "Veggies")
Item.create(name: "Vinegar")
Item.create(name: "Vitamins / Supplements")
Item.create(name: "Vodka")
Item.create(name: "Wax paper")
Item.create(name: "Whipped cream")
Item.create(name: "Whiskey")
Item.create(name: "Wipes")
Item.create(name: "Worcestershire sauce")
Item.create(name: "Yeast")
Item.create(name: "Yogurt")
Item.create(name: "Zucchini")
